apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-api-opa.fullname" . }}-secret
type: Opaque
data:
  JWT_SECRET_KEY: {{ .Values.apiConfig.JWT_SECRET_KEY }}
  INITIAL_PASSWORD: {{ .Values.apiConfig.INITIAL_PASSWORD }}