apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: opa-jwt
  labels:
    app: {{ .Values.opa.name }}
data:
  jwt.rego: "package jwt\n\nimport rego.v1\n\ndefault allow := false\n\nallow if {\n\tclaims.role
    == \"admin\"\n\tinput.method == \"POST\"\n}\n\nallow if {\n\tinput.method == \"GET\"\n\tinput.path
    == \"/login\"\n}\n\nallow if {\n\tinput.method == \"GET\"\n\tinput.path == \"/view\"\n\tinput.authenticated\n}\n\nclaims
    := payload if {\n\tio.jwt.verify_hs256(bearer_token, input.secret_jwt)\n\n\t[_,
    payload, _] := io.jwt.decode(bearer_token)\n}\n\nbearer_token := t if {\n\tv :=
    input.jwt_token\n\tstartswith(v, \"Bearer \")\n\tt := substring(v, count(\"Bearer
    \"), -1)\n}\n"

